"""Initial migration

Revision ID: 9b649e9c1d08
Revises: 
Create Date: 2026-02-21 15:01:04.170611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b649e9c1d08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiration', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('On Duty', 'Off Duty')", name='check_driver_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index('idx_drivers_license_exp', ['license_expiration'], unique=False)
        batch_op.create_index('idx_drivers_name', ['name'], unique=False)
        batch_op.create_index('idx_drivers_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('Manager', 'Dispatcher', 'Safety Officer', 'Financial Analyst')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('max_load_capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity_unit', sa.String(length=10), nullable=False),
    sa.Column('odometer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("capacity_unit IN ('kg', 'tons')", name='check_capacity_unit'),
    sa.CheckConstraint("status IN ('Available', 'On Trip', 'In Shop')", name='check_vehicle_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('idx_vehicles_license_plate', ['license_plate'], unique=False)
        batch_op.create_index('idx_vehicles_status', ['status'], unique=False)

    op.create_table('fuel_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('odometer_reading', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_logs', schema=None) as batch_op:
        batch_op.create_index('idx_fuel_date', ['date'], unique=False)
        batch_op.create_index('idx_fuel_vehicle', ['vehicle_id'], unique=False)

    op.create_table('maintenance_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('In Progress', 'Completed')", name='check_maintenance_status'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.create_index('idx_maintenance_vehicle', ['vehicle_id'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('cargo_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('Draft', 'Dispatched', 'Completed', 'Cancelled')", name='check_trip_status'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index('idx_trips_driver', ['driver_id'], unique=False)
        batch_op.create_index('idx_trips_status', ['status'], unique=False)
        batch_op.create_index('idx_trips_vehicle', ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index('idx_trips_vehicle')
        batch_op.drop_index('idx_trips_status')
        batch_op.drop_index('idx_trips_driver')

    op.drop_table('trips')
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_maintenance_vehicle')

    op.drop_table('maintenance_logs')
    with op.batch_alter_table('fuel_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_fuel_vehicle')
        batch_op.drop_index('idx_fuel_date')

    op.drop_table('fuel_logs')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index('idx_vehicles_status')
        batch_op.drop_index('idx_vehicles_license_plate')

    op.drop_table('vehicles')
    op.drop_table('users')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index('idx_drivers_status')
        batch_op.drop_index('idx_drivers_name')
        batch_op.drop_index('idx_drivers_license_exp')

    op.drop_table('drivers')
    # ### end Alembic commands ###
